# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d4769276f5d2471efc78eafb0bc7f2793fdfda267f7c780f77efed332e5f847816974e4cdeb1812196c93ad75bb4f2a40d008e00f9d29a8555cdfcaf2d4c626c

test:
  secret_key_base: 9b78862e0faa1b08e055bd44eddd58935528df10195044095d2a9ac21dbda9c14e0bdfec36233d4291672721fa1b03bf363246d92e130584652e38b2d58f124b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
